Frontend display a selected post
chris496/ChristopheDumas_BlogPhp pull request #23
Opened 2022-01-22 20:35 UTC by chris496

2022-01-27 17:27 UTC, yoanbernabeu requested changes

2022-01-27 17:27 UTC, yoanbernabeu commented on app/Controller/Controller.php
> +namespace app\blog\Controller;
Dans les namespace première lettre en majuscule

2022-01-27 17:27 UTC, yoanbernabeu commented on app/Controller/Post.php
> +     public function getOnePost(){
Choisir une convention d'écriture

Soit
```php
publblic function foo()
{
...
}
```

Ou

```php
publblic function foo(){
...
}
```

2022-01-27 17:27 UTC, yoanbernabeu commented on app/View/Templates/base.html.twig
> +        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
Pour les assets, mettre un URL relative débutant par **/**

2022-01-27 17:27 UTC, yoanbernabeu commented on app/View/Templates/header.html.twig
> +<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
Corriger indentation

2022-01-27 17:27 UTC, yoanbernabeu commented on database.php
> +        $pdo = new PDO('mysql:host=localhost;dbname=blogphp;charset=utf8', 'root', 'Sql@42ocBdd496');
Basculer la chaine de connexion dans un fichier d'environnement

2022-01-28 13:33 UTC, chris496 commented on app/Controller/Controller.php
> +namespace app\blog\Controller;
ok

2022-01-28 13:59 UTC, chris496 commented on app/Controller/Post.php
> +     public function getOnePost(){
ok

2022-01-28 14:02 UTC, chris496 commented on app/View/Templates/base.html.twig
> +        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
ok

2022-01-28 14:10 UTC, chris496 commented on app/View/Templates/header.html.twig
> +<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
ok

2022-01-28 15:11 UTC, chris496 commented on database.php
> +        $pdo = new PDO('mysql:host=localhost;dbname=blogphp;charset=utf8', 'root', 'Sql@42ocBdd496');
ok

2022-01-28 15:12 UTC, merged